### ISSUE TITLE
result limit rest example is wrong

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/githubio_source#198]
https://sldn.softlayer.com/article/rest#Using_Result_Limits

shoudl be api.softlayer.com/rest/v3/SoftLayer_Account/OpenTickets.json?resultLimit=2&offset=0

**Comment by acamacho82** [comment]
@allmightyspiff  I tested it with `resultLimit=0,2` and `resultLimit=2&offset=0` and I got the same response with both of them

I can update/replace the example as you suggested but maybe it could be better to add another example with `resultLimit=2&offset=0` saying this is another way to limit the response, what do you think?

**Comment by allmightyspiff** [comment]
@acamacho82 I'll update it, I wanted to overhaul this article in any case.

**Comment by allmightyspiff** [comment]
Fixed
