### ISSUE TITLE
Examples of how User_Permission_Role works

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/githubio_source#239]
Need a decent example of how Roles works: https://sldn.softlayer.com/reference/services/SoftLayer_User_Permission_Role/

1. Create Role
2. Add users to role
3. Add resources to role
4. add permissions to role
5. Groups?
6. Edit / Delete Roles

**Comment by ATGE** [comment]
there are  examples of interacting with user permission role (but Edit / Delete Roles are not present):
https://sldn.softlayer.com/python/user_customer_permissions.py/
