### ISSUE TITLE
Broken link to SoftLayer_Network_Service_Vpn_Overrides datatype

### ISSUE THREAD

**Issue by caberos** [softlayer/githubio_source#293]
https://sldn.softlayer.com/reference/datatypes/SoftLayer_Network_Service_Vpn_Overrides/

Under description, the [SoftLayer_User_Customer::updateVPNUser] link returns a 404.

**Comment by allmightyspiff** [comment]
Thanks. I've fixed this in the jira CORE-2152, and will be fixed when that issue is released.
