### ISSUE TITLE
setWebhook Python example (user request)

### ISSUE THREAD

**Issue by William-Scott-Holmes** [softlayer/githubio_source#302]
Quoth the user:
"Hi There , in the following link for setting up setWebhook:
(https://cloud.ibm.com/docs/vsi?topic=virtual-servers-configuring-notifications-for-reclaims-of-transient-virtual-servers)
It's not clear from this doc how to setup this setWebhook in a python env. **Could you please add a real example of ordering a Transient VSI and setting up setWebhook for alerting?**
We are struggling on figuring out how setup this setWebhook parameters.
Regards,
Behzad
(bkoohi)
_Ed. note:  SLDN doc shows parameters but does not include Python code._

**Comment by allmightyspiff** [comment]
@William-Scott-Holmes  https://sldn.softlayer.com/article/TransientGuests/

**Comment by William-Scott-Holmes** [comment]
@bkoohi, please review example code ^^ and let me know what you think.
@allmightyspiff, thanks for the update!
