### ISSUE TITLE
Update old CDN articles to use newer ordering method

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/githubio_source#396]
# TODO
find any old articles that reference interacting with the legacy CDN ( https://sldn.softlayer.com/go/place_order_cdn.go/ for example) and update them to place orders with the new CDN.

Also, combine the CDN articles into a single page.

- *OLD* SoftLayer_Container_Product_Order_Network_ContentDelivery_Account

https://cloud.ibm.com/docs/CDN?topic=CDN-cdn-api-reference
https://cloud.ibm.com/docs/CDN?topic=CDN-code-examples-using-the-cdn-api

**Comment by jiangrij** [comment]
Hi @allmightyspiff, is there any plan when the issue can be fixed?

**Comment by allmightyspiff** [comment]
Caberos has a pull request to make some changes to these articles in #399 , just getting a few minor details fixed and then it will be merged.
