### ISSUE TITLE
Feedback for article - VSI Flavors

### ISSUE THREAD

**Issue by keriwheatley** [softlayer/githubio_source#417]
I can't find any documentation to get the flavor_keyname attached to an existing Virtual Server. Is that information displayed anywhere?

Feedback regarding: https://sldn.softlayer.com/article/vsiflavors/

**Comment by keriwheatley** [comment]
I have figured it out. See the following command for getting profile information about existing Virtual Server.

https://api.softlayer.com/rest/v3/SoftLayer_Account/getVirtualGuests.json?objectMask=mask[billingItem.orderItem.preset]

**Comment by allmightyspiff** [comment]
Glad you got it figured out 👍. We'll add some more context around how to get flavors for an existing VSI.


## TODO
- A a section to /article/vsiflavors/ about how to get the configuration of an existing VSI
- tag the code blocks as json/bash so they highlight properly.
- Add a section on how to order a copy of an existing VSI
