### ISSUE TITLE
Feedback for article - The Catalog

### ISSUE THREAD

**Issue by emarcora** [softlayer/githubio_source#546]
Feedback regarding: https://sldn.softlayer.com/article/catalog/

Hi, what about Virtual Server for VPC service? I'm trying to follow the same steps reported into that article for this service but, unexpectedly, there are no ActivePresets (or at least this API call https://api.softlayer.com/rest/v3.1/SoftLayer_Product_Package/1123/getActivePresets is returning an empty array).

Could you please provide any suggestion on how to get catalog for this service? Thank you!

**Comment by allmightyspiff** [comment]
api.softlayer.com is really only for Classic Infrastructure services. https://cloud.ibm.com/docs/vpc is where you will want to start for VPC related things.

The wider IBM Cloud packages are included in the portal so the invoice can reference them, but if you want updated pricing and ordering information, you will need to use the VPC api, or the [Resource Catalog](https://cloud.ibm.com/apidocs/resource-catalog/global-catalog?code=python) api which has everything that is NOT Classic Infrastructure. 

Hope that helps direct you.
