### ISSUE TITLE
Feedback for python - update_firmware.py

### ISSUE THREAD

**Issue by Sridhar002** [softlayer/githubio_source#644]
Feedback regarding: https://sldn.softlayer.com/python/update_firmware.py/

Hi Team,

Greetings

I was trying this script and i encounter with the below error. 

ython3.11 ./1603248-update.py
Unable to update the firmware:
faultCode= SoftLayer_Exception_Public,
faultString= Server must be offline before firmware update.

Please help me how to fix it.

**Comment by allmightyspiff** [comment]
Hello,

A server needs to be off before it can have its firmware updated. You can call https://sldn.softlayer.com/reference/services/SoftLayer_Hardware_Server/powerOff/ to power off a server.

In keeping with the style of the example, this would work to powerOff a server. Use the [`powerOn`](https://sldn.softlayer.com/reference/services/SoftLayer_Hardware_Server/powerOn/) api to turn it back on.
```python
    result = hardwareServerService.powerOff(id=hardwareId)
    pp(result)
```

I'll update this example later today to be more clear on that. Thanks for the question.

**Comment by Sridhar002** [comment]
Thanks will look forward.
