### ISSUE TITLE
Feedback for article - REST

### ISSUE THREAD

**Issue by webbnh** [softlayer/githubio_source#685]
Feedback regarding: https://sldn.softlayer.com/article/rest/

In the box labeled "Feedback" at the bottom of the page, the "Quick Edit" link is broken.  It currently links to

https://github.com/softlayer/githubio_source/edit/master/content/article/article/rest.md.md

and it should probably be linking to something more like 

https://github.com/softlayer/githubio_source/edit/master/content/article/rest.md

(i.e., without the extra `article/` in the path and without the extra `.md` suffix on the  filename).

**Comment by allmightyspiff** [comment]
Thanks for pointing this out, and your other pull request. I'll check it out.
